siteTitle="FreeCodeCamp"
siteLogo="freecodecamp_logo.svg"
baseColor = "darkgreen"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
]
